import { execFileSync, spawn } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

// import.meta.dirname is undefined under tsx — derive it from the module URL.
export const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')

export function run(command: string, args: string[], opts: { dryRun?: boolean } = {}) {
  console.log(`[run] ${command} ${args.join(' ')}`)
  if (opts.dryRun) return
  const child = spawn(command, args, { cwd: repoRoot, stdio: 'inherit', shell: true })
  child.on('exit', (code) => process.exit(code ?? 0))
}

export function capture(command: string, args: string[]): string {
  return execFileSync(command, args, { cwd: repoRoot, encoding: 'utf8', shell: true })
}

/** Parse `supabase status -o env` output into a key/value map. */
export function supabaseStatus(): Record<string, string> | null {
  try {
    const out = capture('pnpm', ['exec', 'supabase', 'status', '-o', 'env'])
    const env: Record<string, string> = {}
    for (const line of out.split(/\r?\n/)) {
      const match = /^([A-Z0-9_]+)="?([^"]*)"?$/.exec(line.trim())
      if (match && match[1] && match[2] !== undefined) env[match[1]] = match[2]!
    }
    return Object.keys(env).length > 0 ? env : null
  } catch {
    return null
  }
}

export function mask(value: string | undefined): string {
  if (!value) return '(not set)'
  return `${value.slice(0, 6)}…[set]`
}

export function writeEnvFile(path: string, entries: Record<string, string>) {
  const body =
    Object.entries(entries)
      .map(([k, v]) => `${k}=${v}`)
      .join('\n') + '\n'
  writeFileSync(path, `# Generated by scripts/dev.ts — do not edit; do not commit.\n${body}`)
  console.log(`[env] wrote ${path}`)
}
