// Repeatable version of the 2026-09-04 NTFS-migration check: does a fresh NTFS
// clone of this repo actually fix the exFAT/Turbopack local-build blocker
// (CLAUDE.md's "Key standing decisions" exFAT bullet, docs/01)?
//
//   pnpm exec tsx scripts/verify-ntfs-build.ts               # default target: C:\Solutions Platform
//   pnpm exec tsx scripts/verify-ntfs-build.ts D:\some\other\repo C:\ntfs-check
//
// WHAT THIS DOES, safely and repeatably, with ZERO shared-state risk:
//   1. Fresh-clones this repo's origin into the target NTFS directory (wipes and
//      re-clones if the target already exists, so every run starts genuinely clean).
//   2. Copies every git-ignored file/dir the source repo actually has — discovered
//      live via `git status --porcelain --ignored`, NOT a hardcoded list, so a new
//      .env file or founder note added later is picked up automatically. Skips only
//      the pure build-artifact patterns (node_modules, .turbo, .next, dist, etc.) —
//      those get regenerated by install/build anyway.
//   3. `pnpm install`, then the actual test: `pnpm --filter web build`.
//   4. Reports PASS/FAIL with timing. That single command succeeding is the whole
//      proof — it needs no Docker/Supabase at all.
//
// WHAT THIS DELIBERATELY DOES NOT DO: touch Docker or Supabase. The fuller
// payoff test (a local e2e run) needs the shared local Supabase stack, which
// only one drive-copy can use at a time (fixed ports) — that step requires a
// human judgment call about whether another Claude session or dev server is
// using it right now, so it is NOT automated here. If the build step below
// passes and you also want the e2e half, do it by hand, from the target dir:
//   pnpm exec supabase stop        (from whichever copy is currently running it)
//   pnpm exec supabase start       (from the target dir)
//   docker restart supabase_kong_<project>   (project name = target dir's basename)
//   pnpm exec supabase db reset && pnpm seed
//   CI=true pnpm --filter web exec playwright test
// See docs/history/platform-journal.md's 2026-09-04 "NTFS MIGRATION" entry for
// the full narrative (incl. the "Compose project identity is the directory
// BASENAME only" gotcha — a same-named copy on another drive shares containers).
import { execSync } from 'node:child_process'
import * as fs from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const sourceRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const target = resolve(process.argv[3] ?? 'C:\\Solutions Platform')
const sourceArg = process.argv[2] ? resolve(process.argv[2]) : sourceRoot

// Regenerated by install/build — never worth copying, and copying them can
// actively cause stale-artifact confusion (a .next built for the WRONG drive).
const SKIP_PATTERNS = [
  /(^|[\\/])node_modules([\\/]|$)/,
  /(^|[\\/])\.turbo([\\/]|$)/,
  /(^|[\\/])\.next([\\/]|$)/,
  /(^|[\\/])\.vercel([\\/]|$)/,
  /(^|[\\/])dist([\\/]|$)/,
  /(^|[\\/])test-results([\\/]|$)/,
  /(^|[\\/])supabase[\\/]\.branches([\\/]|$)/,
  /(^|[\\/])supabase[\\/]\.temp([\\/]|$)/,
  /tsconfig\.tsbuildinfo$/,
  /next-env\.d\.ts$/,
]

function resolvePnpm(): string {
  for (const candidate of ['pnpm', 'corepack pnpm']) {
    try {
      execSync(`${candidate} --version`, { stdio: 'ignore' })
      return candidate
    } catch {
      // try the next candidate — see CLAUDE.md's documented pnpm-off-PATH gotcha
    }
  }
  throw new Error('Neither `pnpm` nor `corepack pnpm` resolved — see CLAUDE.md pnpm-PATH gotcha')
}

function sh(command: string, cwd: string) {
  console.log(`\n[run] (cwd=${cwd}) ${command}`)
  execSync(command, { cwd, stdio: 'inherit' })
}

function shOut(command: string, cwd: string): string {
  return execSync(command, { cwd, encoding: 'utf8' })
}

function copyIgnoredFiles(from: string, to: string) {
  const raw = shOut('git status --porcelain --ignored', from)
  const ignored = raw
    .split(/\r?\n/)
    .filter((l) => l.startsWith('!! '))
    .map((l) => l.slice(3).replace(/\/$/, ''))

  let copied = 0
  let skipped = 0
  for (const rel of ignored) {
    if (SKIP_PATTERNS.some((p) => p.test(rel))) {
      skipped++
      continue
    }
    const src = join(from, rel)
    const dst = join(to, rel)
    fs.mkdirSync(dirname(dst), { recursive: true })
    fs.cpSync(src, dst, { recursive: true })
    copied++
    console.log(`  copied: ${rel}`)
  }
  console.log(`\n[copy] ${copied} ignored file(s)/dir(s) copied, ${skipped} build-artifact pattern(s) skipped`)

  // Prove it: every copied top-level file must be byte-identical (dirs are
  // trusted — cpSync is not diffed recursively here, just existence-checked).
  let mismatches = 0
  for (const rel of ignored) {
    if (SKIP_PATTERNS.some((p) => p.test(rel))) continue
    const src = join(from, rel)
    const dst = join(to, rel)
    if (fs.statSync(src).isDirectory()) continue
    const same = fs.readFileSync(src).equals(fs.readFileSync(dst))
    if (!same) {
      mismatches++
      console.log(`  MISMATCH: ${rel}`)
    }
  }
  if (mismatches > 0) throw new Error(`${mismatches} copied file(s) are not byte-identical`)
  console.log('[copy] CONTROL: every copied file verified byte-identical')
}

const startedAt = Date.now()
console.log(`NTFS build-fix verification\n  source: ${sourceArg}\n  target: ${target}\n`)

const pnpm = resolvePnpm()
console.log(`[pnpm] resolved as: ${pnpm}`)

if (fs.existsSync(target)) {
  console.log(`[clone] target exists — wiping for a genuinely fresh run: ${target}`)
  fs.rmSync(target, { recursive: true, force: true })
}

const originUrl = shOut('git remote get-url origin', sourceArg).trim()
const targetParent = dirname(target)
if (!fs.existsSync(targetParent)) fs.mkdirSync(targetParent, { recursive: true })
sh(`git clone "${originUrl}" "${target}"`, targetParent)

copyIgnoredFiles(sourceArg, target)

sh(`${pnpm} install`, target)

let buildOk = true
try {
  sh(`${pnpm} --filter web build`, target)
} catch {
  buildOk = false
}

const elapsedMin = ((Date.now() - startedAt) / 60000).toFixed(1)
console.log(`\n${'='.repeat(60)}`)
console.log(buildOk ? `PASS — build succeeded on NTFS (${elapsedMin} min)` : `FAIL — build failed on NTFS too (${elapsedMin} min)`)
console.log(`${'='.repeat(60)}`)
console.log(`\nTarget copy left at: ${target}`)
console.log('For the optional e2e half, see this script\'s header comment.')
process.exit(buildOk ? 0 : 1)
